baseurl = "https://hgfkeep.github.io"
title = "HGFKEEP"

theme = "hugo-coder"

languagecode = "zh-cn"
defaultcontentlanguage = "zh-cn"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "hgfkeep"

[params]
    author = "heguangfu"
    description = "一条河流分割了过去和未来"
    keywords = "dev,designer"
    info = "welcome!"
    avatarurl = "images/avatar.jpg"
    footercontent = "<div style='padding:2px'><div style='font-weight: bold;'>遇见你是我的幸运-jxn❤️</div><br />感谢阅读，如果有问题请您留言<br /></div><div style=''><img src='https://licensebuttons.net/l/by-nc-sa/3.0/88x31.png'> </div>"

    dateformat = "2006-01-02"

    hideCredits = false
    hideCopyright = false

    # Git Commit in Footer, uncomment the line below to enable it.
    #commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Use inverted colors
    inverted = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = ["css/code.css","css/custom.css"]
    
    # Custom JS
    custom_js = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/hgfkeep/"


[languages]

    
    [languages.zh-cn]
        languagename = "Chinese"

        [[languages.zh-cn.menu.main]]
        name = "关于"
        weight = 1
        url = "/about/"

        [[languages.zh-cn.menu.main]]
        name = "博客"
        weight = 2
        url = "/posts/"

        [[languages.zh-cn.menu.main]]
        name = "分类"
        weight = 3
        url = "/categories/"

        [[languages.zh-cn.menu.main]]
        name = "系列"
        weight = 4
        url = "/series/"

        [[languages.zh-cn.menu.main]]
        name = "目标"
        weight = 5
        url = "/flag/"

        [[languages.zh-cn.menu.main]]
        name = "联系我"
        weight = 6
        url = "/contact/"


